---

name: Build and release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags: ["*"]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: ./build.sh
        env:
          CI_COMMIT_REF_NAME: ${{ github.ref_name }}
      - name: Create release
        run: gh release create ${{ github.ref_name }} --generate-notes bin/*
        env:
          GH_TOKEN: ${{ github.token }}
